services:
  db:
    image: mysql:8.4.7
    container_name: mysql847
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: odissey_travel
      MYSQL_USER: odissey
      MYSQL_PASSWORD: Password123!
    ports:
      - "3309:3306"
    volumes:
      - C:/Users/Public/docker_data/mysql/8.4.7:/var/lib/mysql
volumes:
  db_data: